### ISSUE TITLE
localhost:3000/ でアクセスした時のページについて

### ISSUE THREAD

**Issue by h5y1m141** [shiro615/futsal_app#9]
- [x] 現在の作りだとあらかじめ期待されてる値がデータベースに存在してないと以下エラーになるのでそこの対処を行う
  - 考えられるアプローチ１：ひとまずデータベースへの登録関係なくトップページは表示されるように修正する
  - 考えられるアプローチ２：db/seed.rbにて、トップページで利用するデータを登録できるようにする

![shot-2015-01-09-18 20 21](https://cloud.githubusercontent.com/assets/950924/5677605/36c2d75c-982c-11e4-879f-ae8692c1f682.png)

**Comment by shiro615** [comment]
db/seed.rbにトップページで利用するデータを登録できるスクリプトを書きました。
